# Generated by Django 5.1.7 on 2026-01-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilitybill',
            name='user',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='UtilityBill',
        ),
    ]
