# Generated by Django 5.1.7 on 2026-01-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('utility', 'Utility'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
