# Generated by Django 5.1.7 on 2026-01-16 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_userprofile_email_userprofile_full_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUtility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('utility_type', models.CharField(max_length=50)),
                ('provider_name', models.CharField(blank=True, max_length=150)),
                ('consumer_number', models.CharField(blank=True, db_column='consumr_number', max_length=100)),
                ('water_connection_number', models.CharField(blank=True, max_length=100)),
                ('gas_connection_number', models.CharField(blank=True, max_length=100)),
                ('wifi_consumer_id', models.CharField(blank=True, max_length=100)),
                ('dth_subscriber_id', models.CharField(blank=True, max_length=100)),
                ('meter_number', models.CharField(blank=True, max_length=100)),
                ('connection_type', models.CharField(blank=True, max_length=50)),
                ('plan_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creeated_at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_utility',
                'indexes': [models.Index(fields=['utility_type'], name='user_utilit_utility_1b1218_idx'), models.Index(fields=['user_name'], name='user_utilit_user_na_d85a3d_idx')],
            },
        ),
    ]
