# Generated by Django 5.1.7 on 2026-01-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_userutility'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=64, unique=True)),
                ('utility_type', models.CharField(max_length=50)),
                ('provider_name', models.CharField(blank=True, max_length=150)),
                ('consumer_name', models.CharField(blank=True, max_length=150)),
                ('consumer_number', models.CharField(blank=True, max_length=100)),
                ('water_connection_number', models.CharField(blank=True, max_length=100)),
                ('gas_consumer_id', models.CharField(blank=True, max_length=100)),
                ('wifi_consumer_id', models.CharField(blank=True, max_length=100)),
                ('dth_subscriber_id', models.CharField(blank=True, max_length=100)),
                ('plan_name', models.CharField(blank=True, max_length=100)),
                ('dth_package_name', models.CharField(blank=True, max_length=100)),
                ('specified_utility_type', models.CharField(blank=True, max_length=100)),
                ('previous_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('units_consumed', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reading_date', models.DateField()),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'generated_bill',
                'indexes': [models.Index(fields=['utility_type'], name='generated_b_utility_da1d57_idx'), models.Index(fields=['bill_id'], name='generated_b_bill_id_c7faca_idx')],
            },
        ),
        migrations.CreateModel(
            name='UtilityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_type', models.CharField(max_length=50)),
                ('bill_id', models.CharField(max_length=64)),
                ('consumer_name', models.CharField(blank=True, max_length=150)),
                ('consumer_id', models.CharField(blank=True, max_length=150)),
                ('previous_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'utility_bill',
                'indexes': [models.Index(fields=['utility_type'], name='utility_bil_utility_e33429_idx'), models.Index(fields=['bill_id'], name='utility_bil_bill_id_f4dfcc_idx')],
            },
        ),
    ]
