# Generated by Django 4.2 on 2026-01-30
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_userprofile_otp_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('provider_name', models.CharField(max_length=150)),
                ('sender_role', models.CharField(choices=[('user', 'User'), ('utility', 'Utility'), ('system', 'System')], max_length=20)),
                ('sender_username', models.CharField(blank=True, max_length=150)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user_name'], name='bills_chat_user_na_1234'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['provider_name'], name='bills_chat_provide_1234'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['created_at'], name='bills_chat_created_1234'),
        ),
    ]
