# Generated by Django 5.1 on 2026-01-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0010_chatmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_messag_user_na_9bd9ab_idx',
            old_name='bills_chat_user_na_1234',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_messag_provide_b986d9_idx',
            old_name='bills_chat_provide_1234',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_messag_created_b6b51c_idx',
            old_name='bills_chat_created_1234',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
