# Generated by Django 5.1.7 on 2026-02-21 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0015_paymentmethod'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentmethod',
            new_name='payment_met_user_id_f282cf_idx',
            old_name='payment_met_user_id_created_idx',
        ),
    ]
