# Generated by Django 5.1.7 on 2026-02-21 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0016_rename_payment_met_user_id_created_idx_payment_met_user_id_f282cf_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('bill_added', 'Bill Added'), ('bill_generated', 'Bill Generated'), ('payment_initiated', 'Payment Initiated'), ('payment_pending', 'Payment Pending'), ('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected'), ('bill_due', 'Bill Due'), ('profile_updated', 'Profile Updated')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('utility_type', models.CharField(blank=True, max_length=50)),
                ('bill_id', models.CharField(blank=True, max_length=64)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_366c29_idx'), models.Index(fields=['user', 'read'], name='notificatio_user_id_d59197_idx'), models.Index(fields=['utility_type'], name='notificatio_utility_2adc3f_idx')],
            },
        ),
    ]
