# Generated by Django 5.1.7 on 2026-02-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0018_userprofile_utility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('bill_added', 'Bill Added'), ('bill_generated', 'Bill Generated'), ('payment_initiated', 'Payment Initiated'), ('payment_pending', 'Payment Pending'), ('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected'), ('bill_due', 'Bill Due'), ('bill_overdue', 'Bill Overdue'), ('reward_earned', 'Reward Earned'), ('profile_updated', 'Profile Updated')], max_length=50),
        ),
    ]
