# Generated by Django 5.1.7 on 2026-02-23 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0020_chatmessage_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=150)),
                ('utility_type', models.CharField(max_length=50)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider_name', '-created_at'], name='review_provide_251db9_idx'), models.Index(fields=['utility_type', '-created_at'], name='review_utility_fa69a4_idx'), models.Index(fields=['user', '-created_at'], name='review_user_id_f72d55_idx')],
            },
        ),
    ]
