# Generated by Django 5.1.7 on 2026-02-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0021_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitybill',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='reading_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
